import path from 'path';
import { fileURLToPath } from 'url';

import eslintComments from '@eslint-community/eslint-plugin-eslint-comments/configs';
import { FlatCompat } from '@eslint/eslintrc';
import eslint from '@eslint/js';
import nextPlugin from '@next/eslint-plugin-next';
import prettierConfig from 'eslint-config-prettier';
import eslintPluginImportX from 'eslint-plugin-import-x';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import react from '@eslint-react/eslint-plugin';
import reactHooks from 'eslint-plugin-react-hooks';
import tailwind from 'eslint-plugin-tailwindcss';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import perfectionist from 'eslint-plugin-perfectionist';
import jsdoc from 'eslint-plugin-jsdoc';
import reactRefresh from 'eslint-plugin-react-refresh';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

export default tseslint.config(
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'eslint.config.js',
      'lingui.config.js',
      'next.config.mjs',
      'postcss.config.mjs',
      'src/utils/database.types.ts', // This file is generated by Supabase
    ],
  },
  perfectionist.configs['recommended-natural'],
  jsdoc.configs['flat/recommended-typescript-error'],
  eslint.configs.recommended,
  eslintComments.recommended,
  eslintPluginImportX.flatConfigs.recommended,
  eslintPluginImportX.flatConfigs.typescript,
  ...tseslint.configs.recommendedTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  prettierConfig,
  ...tailwind.configs['flat/recommended'],
  {
    files: ['**/*.{js,mjs,cjs,jsx,mjsx,ts,tsx,mtsx}'],
    ...react.configs.recommendedTypeChecked,
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      react,
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
      '@next/next': nextPlugin,
      'react-refresh': reactRefresh,
    },
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        ...globals.browser,
      },
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    settings: {
      react: {
        version: 'detect',
      },
      'import-x/parsers': {
        '@typescript-eslint/parser': ['.ts', '.mts', '.cts', '.tsx', '.d.ts'],
      },
      'import-x/resolver': {
        'eslint-import-resolver-node': {
          name: 'node',
          options: {
            extensions: [
              '.js',
              '.mjs',
              '.cjs',
              '.jsx',
              '.mjsx',
              '.ts',
              '.tsx',
              '.mtsx',
            ],
          },
        },
        'eslint-import-resolver-typescript': {
          name: 'typescript',
          options: {
            alwaysTryTypes: true,
          },
        },
      },
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      ...jsxA11y.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      // Ignore any module starting with ~icons because they are virtual modules
      'import-x/no-unresolved': [2, { ignore: ['^~icons/'] }],
      // Allow custom CSS classes, we barely use them and they come from shadcn.
      'tailwindcss/no-custom-classname': 0,
    },
  },
  {
    files: ['**/components/ui/*.tsx'],
    rules: {},
  },
);
