import path from 'path';
import { fileURLToPath } from 'url';

import eslintComments from '@eslint-community/eslint-plugin-eslint-comments/configs';
import { FlatCompat } from '@eslint/eslintrc';
import eslint from '@eslint/js';
import nextPlugin from '@next/eslint-plugin-next';
import prettierConfig from 'eslint-config-prettier';
import eslintPluginImportX from 'eslint-plugin-import-x';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import react from '@eslint-react/eslint-plugin';
import reactHooks from 'eslint-plugin-react-hooks';
import tailwind from 'eslint-plugin-tailwindcss';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import perfectionist from 'eslint-plugin-perfectionist';
import jsdoc from 'eslint-plugin-jsdoc';
import eslintPluginUnicorn from 'eslint-plugin-unicorn';
import vitest from '@vitest/eslint-plugin';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

export default tseslint.config(
  {
    ignores: [
      'next-env.d.ts',
      '.next/**',
      'coverage/**',
      'node_modules/**',
      'eslint.config.js',
      'lingui.config.js',
      'next.config.mjs',
      'postcss.config.mjs',
      'src/infrastructure/database/models/database.types.ts', // This file is generated by Supabase
    ],
  },
  perfectionist.configs['recommended-natural'],
  jsdoc.configs['flat/recommended-typescript-error'],
  eslint.configs.recommended,
  eslintComments.recommended,
  eslintPluginImportX.flatConfigs.recommended,
  eslintPluginImportX.flatConfigs.typescript,
  ...tseslint.configs.recommendedTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  prettierConfig,
  ...tailwind.configs['flat/recommended'],
  {
    files: ['**/*.{js,mjs,cjs,jsx,mjsx,ts,tsx,mtsx}'],
    ...react.configs.recommendedTypeChecked,
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      react,
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
      '@next/next': nextPlugin,
      unicorn: eslintPluginUnicorn,
    },
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        ...globals.builtin,
        ...globals.browser,
      },
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    settings: {
      vitest: {
        typecheck: true,
      },
      react: {
        version: 'detect',
      },
      'import-x/parsers': {
        '@typescript-eslint/parser': ['.ts', '.mts', '.cts', '.tsx', '.d.ts'],
      },
      'import-x/resolver': {
        'eslint-import-resolver-node': {
          name: 'node',
          options: {
            extensions: [
              '.js',
              '.mjs',
              '.cjs',
              '.jsx',
              '.mjsx',
              '.ts',
              '.tsx',
              '.mtsx',
            ],
          },
        },
        'eslint-import-resolver-typescript': {
          name: 'typescript',
          options: {
            alwaysTryTypes: true,
          },
        },
      },
    },
    rules: {
      ...eslintPluginUnicorn.configs['flat/recommended'].rules,
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      ...jsxA11y.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      // Allow custom CSS classes, we barely use them and they come from shadcn.
      'tailwindcss/no-custom-classname': 0,
      // Allow using null, as it is a valid value in TypeScript and is standard in multiple libraries.
      'unicorn/no-null': 0,
      // Require an explanation for disabled rules.
      '@eslint-community/eslint-comments/require-description': 2,
      // There's a tendency to just repeat the names of parameters in JSDoc comments, so check for that.
      'jsdoc/informative-docs': 2,
      // Try to enforce a consistent order for JSDoc descriptions.
      'jsdoc/require-description-complete-sentence': 2,
      // We use arrow functions to handle form submissions, and moving them out of the component breaks the submission.
      'unicorn/consistent-function-scoping': [
        2,
        { checkArrowFunctions: false },
      ],
    },
  },
  {
    files: ['**/components/ui/*.tsx'],
    rules: {},
  },
  {
    // Rules for test files.
    files: ['**/*.spec.{js,ts}'],
    plugins: {
      vitest,
    },
    rules: {
      ...vitest.configs.recommended.rules,
    },
  },
);
