create extension if not exists "isn" with schema "extensions";


create type "public"."app_permission" as enum ('movie.delete', 'movie.update', 'movie.create', 'person.delete', 'person.update', 'person.create', 'series.delete', 'series.update', 'series.create', 'studio.delete', 'studio.update', 'studio.create', 'category.delete', 'category.update', 'category.create', 'label.delete', 'label.update', 'label.create', 'image.delete', 'image.update', 'image.create', 'job.delete', 'job.update', 'job.create', 'role.delete', 'role.update', 'role.create', 'tag.delete', 'tag.update', 'tag.create');

create type "public"."app_role" as enum ('admin', 'moderator', 'user', 'banned');

create type "public"."bra_size" as enum ('AA', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M');

create type "public"."image_type" as enum ('front_cover', 'full_cover', 'art', 'disc', 'profile', 'logo', 'screenshot');

create type "public"."media_format" as enum ('DVD', 'Blu-ray', 'Blu-ray 4K', 'Digital', 'VHS', 'LaserDisc', 'UMD Video', 'Video CD');

drop trigger if exists "update_role_age_after_person_update" on "public"."persons";

drop policy "Enable read access for all users" on "public"."category_movies";

revoke delete on table "public"."category_movies" from "anon";

revoke insert on table "public"."category_movies" from "anon";

revoke references on table "public"."category_movies" from "anon";

revoke select on table "public"."category_movies" from "anon";

revoke trigger on table "public"."category_movies" from "anon";

revoke truncate on table "public"."category_movies" from "anon";

revoke update on table "public"."category_movies" from "anon";

revoke delete on table "public"."category_movies" from "authenticated";

revoke insert on table "public"."category_movies" from "authenticated";

revoke references on table "public"."category_movies" from "authenticated";

revoke select on table "public"."category_movies" from "authenticated";

revoke trigger on table "public"."category_movies" from "authenticated";

revoke truncate on table "public"."category_movies" from "authenticated";

revoke update on table "public"."category_movies" from "authenticated";

revoke delete on table "public"."category_movies" from "service_role";

revoke insert on table "public"."category_movies" from "service_role";

revoke references on table "public"."category_movies" from "service_role";

revoke select on table "public"."category_movies" from "service_role";

revoke trigger on table "public"."category_movies" from "service_role";

revoke truncate on table "public"."category_movies" from "service_role";

revoke update on table "public"."category_movies" from "service_role";

alter table "public"."category_movies" drop constraint "category_movies_category_id";

alter table "public"."category_movies" drop constraint "category_movies_movie_id";

alter table "public"."profiles" drop constraint "profiles_username_key";

alter table "public"."profiles" drop constraint "username_length";

alter table "public"."category_movies" drop constraint "category_movies_pkey";

drop index if exists "public"."profiles_username_key";

drop index if exists "public"."category_movies_category_id_idx";

drop index if exists "public"."category_movies_movie_id_idx";

drop index if exists "public"."category_movies_pkey";

drop table "public"."category_movies";

create table "public"."images" (
    "id" bigint generated by default as identity not null,
    "uuid" text not null,
    "type" image_type not null,
    "created_at" timestamp with time zone not null default now(),
    "uploader" uuid not null default auth.uid()
);


alter table "public"."images" enable row level security;

create table "public"."movie_images" (
    "id" bigint generated by default as identity not null,
    "movie_id" bigint not null,
    "image_id" bigint not null,
    "sequence" integer
);


alter table "public"."movie_images" enable row level security;

create table "public"."person_images" (
    "id" bigint generated by default as identity not null,
    "person_id" bigint not null,
    "image_id" bigint not null
);


alter table "public"."person_images" enable row level security;

create table "public"."persons_aliases" (
    "id" bigint generated by default as identity not null,
    "person_id" bigint not null,
    "name" text,
    "original_name" text
);


alter table "public"."persons_aliases" enable row level security;

create table "public"."role_permissions" (
    "id" bigint generated by default as identity not null,
    "role" app_role not null,
    "permission" app_permission not null
);


alter table "public"."role_permissions" enable row level security;

create table "public"."tags" (
    "category_id" bigint not null,
    "movie_id" bigint not null
);


alter table "public"."tags" enable row level security;

create table "public"."user_roles" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "role" app_role not null
);


alter table "public"."user_roles" enable row level security;

create table "public"."views" (
    "id" bigint generated by default as identity not null,
    "client_hash" text,
    "item_type" text,
    "item_id" bigint,
    "date" date not null default CURRENT_DATE
);


alter table "public"."views" enable row level security;

alter table "public"."categories" add column "parent_id" bigint;

alter table "public"."labels" alter column "create_time" set default now();

alter table "public"."labels" alter column "update_time" set default now();

alter table "public"."movies" drop column "art_url";

alter table "public"."movies" drop column "thumb_url";

alter table "public"."movies" add column "barcode" ean13;

alter table "public"."movies" add column "format" media_format;

alter table "public"."movies" add column "front_cover_url" text;

alter table "public"."movies" add column "full_cover_url" text;

alter table "public"."movies" add column "has_nudity" boolean not null default false;

alter table "public"."movies" add column "popularity" double precision default '0'::double precision;

alter table "public"."movies" alter column "create_time" set default now();

alter table "public"."movies" alter column "update_time" set default now();

alter table "public"."persons" drop column "art_url";

alter table "public"."persons" drop column "thumb_url";

alter table "public"."persons" add column "bust_size" smallint;

alter table "public"."persons" add column "cup_size" bra_size;

alter table "public"."persons" add column "height" smallint;

alter table "public"."persons" add column "hips_size" smallint;

alter table "public"."persons" add column "popularity" double precision default '0'::double precision;

alter table "public"."persons" add column "profile_url" text;

alter table "public"."persons" add column "waist_size" smallint;

alter table "public"."persons" alter column "create_time" set default now();

alter table "public"."persons" alter column "update_time" set default now();

alter table "public"."profiles" drop column "updated_at";

alter table "public"."profiles" add column "avatar_url" text;

alter table "public"."profiles" add column "create_time" timestamp with time zone not null default now();

alter table "public"."profiles" add column "email" text;

alter table "public"."series" alter column "create_time" set default now();

alter table "public"."series" alter column "update_time" set default now();

alter table "public"."studios" add column "fts_doc" tsvector generated always as (to_tsvector('english'::regconfig, (((COALESCE(name, ''::character varying))::text || ' '::text) || (COALESCE(original_name, ''::character varying))::text))) stored;

alter table "public"."studios" add column "homepage" text;

alter table "public"."studios" alter column "create_time" set default now();

alter table "public"."studios" alter column "update_time" set default now();

CREATE INDEX categories_parent_id_idx ON public.categories USING btree (parent_id);

CREATE UNIQUE INDEX images_pkey ON public.images USING btree (id);

CREATE INDEX images_uploader_idx ON public.images USING btree (uploader);

CREATE UNIQUE INDEX images_uuid_key ON public.images USING btree (uuid);

CREATE INDEX jobs_movie_id_idx ON public.jobs USING btree (movie_id);

CREATE INDEX jobs_person_id_idx ON public.jobs USING btree (person_id);

CREATE INDEX movie_images_image_id_idx ON public.movie_images USING btree (image_id);

CREATE INDEX movie_images_movie_id_idx ON public.movie_images USING btree (movie_id);

CREATE UNIQUE INDEX movie_images_pkey ON public.movie_images USING btree (id);

CREATE INDEX movies_create_time_idx ON public.movies USING btree (create_time);

CREATE UNIQUE INDEX movies_front_cover_url_key ON public.movies USING btree (front_cover_url);

CREATE UNIQUE INDEX movies_full_cover_url_key ON public.movies USING btree (full_cover_url);

CREATE INDEX movies_label_id_idx ON public.movies USING btree (label_id);

CREATE INDEX movies_series_id_idx ON public.movies USING btree (series_id);

CREATE INDEX movies_studio_id_idx ON public.movies USING btree (studio_id);

CREATE INDEX movies_update_time_idx ON public.movies USING btree (update_time);

CREATE INDEX person_images_image_id_idx ON public.person_images USING btree (image_id);

CREATE INDEX person_images_person_id_idx ON public.person_images USING btree (person_id);

CREATE UNIQUE INDEX person_images_pkey ON public.person_images USING btree (id);

CREATE INDEX persons_aliases_person_id_idx ON public.persons_aliases USING btree (person_id);

CREATE UNIQUE INDEX persons_aliases_pkey ON public.persons_aliases USING btree (id);

CREATE INDEX persons_popularity_idx ON public.persons USING btree (popularity);

CREATE UNIQUE INDEX persons_profile_url_key ON public.persons USING btree (profile_url);

CREATE UNIQUE INDEX role_permissions_pkey ON public.role_permissions USING btree (id);

CREATE UNIQUE INDEX role_permissions_role_permission_key ON public.role_permissions USING btree (role, permission);

CREATE INDEX roles_movie_id_idx ON public.roles USING btree (movie_id);

CREATE INDEX roles_person_id_idx ON public.roles USING btree (person_id);

CREATE INDEX studios_fts_doc_idx ON public.studios USING gin (fts_doc);

CREATE UNIQUE INDEX user_roles_pkey ON public.user_roles USING btree (id);

CREATE UNIQUE INDEX user_roles_user_id_role_key ON public.user_roles USING btree (user_id, role);

CREATE UNIQUE INDEX views_client_hash_item_type_item_id_date_idx ON public.views USING btree (client_hash, item_type, item_id, date);

CREATE UNIQUE INDEX views_pkey ON public.views USING btree (id);

CREATE INDEX category_movies_category_id_idx ON public.tags USING btree (category_id);

CREATE INDEX category_movies_movie_id_idx ON public.tags USING btree (movie_id);

CREATE UNIQUE INDEX category_movies_pkey ON public.tags USING btree (category_id, movie_id);

alter table "public"."images" add constraint "images_pkey" PRIMARY KEY using index "images_pkey";

alter table "public"."movie_images" add constraint "movie_images_pkey" PRIMARY KEY using index "movie_images_pkey";

alter table "public"."person_images" add constraint "person_images_pkey" PRIMARY KEY using index "person_images_pkey";

alter table "public"."persons_aliases" add constraint "persons_aliases_pkey" PRIMARY KEY using index "persons_aliases_pkey";

alter table "public"."role_permissions" add constraint "role_permissions_pkey" PRIMARY KEY using index "role_permissions_pkey";

alter table "public"."tags" add constraint "category_movies_pkey" PRIMARY KEY using index "category_movies_pkey";

alter table "public"."user_roles" add constraint "user_roles_pkey" PRIMARY KEY using index "user_roles_pkey";

alter table "public"."views" add constraint "views_pkey" PRIMARY KEY using index "views_pkey";

alter table "public"."categories" add constraint "categories_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES categories(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."categories" validate constraint "categories_parent_id_fkey";

alter table "public"."images" add constraint "images_uploader_fkey" FOREIGN KEY (uploader) REFERENCES profiles(id) not valid;

alter table "public"."images" validate constraint "images_uploader_fkey";

alter table "public"."images" add constraint "images_uuid_key" UNIQUE using index "images_uuid_key";

alter table "public"."movie_images" add constraint "movie_images_image_id_fkey" FOREIGN KEY (image_id) REFERENCES images(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."movie_images" validate constraint "movie_images_image_id_fkey";

alter table "public"."movie_images" add constraint "movie_images_movie_id_fkey" FOREIGN KEY (movie_id) REFERENCES movies(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."movie_images" validate constraint "movie_images_movie_id_fkey";

alter table "public"."movies" add constraint "movies_front_cover_url_key" UNIQUE using index "movies_front_cover_url_key";

alter table "public"."movies" add constraint "movies_full_cover_url_key" UNIQUE using index "movies_full_cover_url_key";

alter table "public"."person_images" add constraint "person_images_image_id_fkey" FOREIGN KEY (image_id) REFERENCES images(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."person_images" validate constraint "person_images_image_id_fkey";

alter table "public"."person_images" add constraint "person_images_person_id_fkey" FOREIGN KEY (person_id) REFERENCES persons(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."person_images" validate constraint "person_images_person_id_fkey";

alter table "public"."persons" add constraint "persons_profile_url_key" UNIQUE using index "persons_profile_url_key";

alter table "public"."persons_aliases" add constraint "persons_aliases_person_id_fkey" FOREIGN KEY (person_id) REFERENCES persons(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."persons_aliases" validate constraint "persons_aliases_person_id_fkey";

alter table "public"."role_permissions" add constraint "role_permissions_role_permission_key" UNIQUE using index "role_permissions_role_permission_key";

alter table "public"."tags" add constraint "category_movies_category_id" FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE not valid;

alter table "public"."tags" validate constraint "category_movies_category_id";

alter table "public"."tags" add constraint "category_movies_movie_id" FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE not valid;

alter table "public"."tags" validate constraint "category_movies_movie_id";

alter table "public"."user_roles" add constraint "user_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."user_roles" validate constraint "user_roles_user_id_fkey";

alter table "public"."user_roles" add constraint "user_roles_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."user_roles" validate constraint "user_roles_user_id_fkey1";

alter table "public"."user_roles" add constraint "user_roles_user_id_role_key" UNIQUE using index "user_roles_user_id_role_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.authorize(requested_permission app_permission)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  bind_permissions int;
  user_role public.app_role;
begin
  -- Fetch user role once and store it to reduce number of calls
  select (auth.jwt() ->> 'user_role')::public.app_role into user_role;

  select count(*)
  into bind_permissions
  from public.role_permissions
  where role_permissions.permission = requested_permission
    and role_permissions.role = user_role;

  return bind_permissions > 0;
end;
$function$
;

create materialized view "public"."current_counts" as  SELECT ( SELECT count(*) AS count
           FROM movies) AS movie_count,
    ( SELECT count(*) AS count
           FROM persons) AS person_count,
    ( SELECT count(*) AS count
           FROM studios) AS studio_count,
    ( SELECT count(*) AS count
           FROM series) AS series_count,
    ( SELECT count(*) AS count
           FROM labels) AS label_count,
    ( SELECT count(*) AS count
           FROM tags) AS tag_count;


CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
  declare
    claims jsonb;
    user_role public.app_role;
  begin
    -- Fetch the user role in the user_roles table
    select role into user_role from public.user_roles where user_id = (event->>'user_id')::uuid;

    claims := event->'claims';

    if user_role is not null then
      -- Set the claim
      claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
    else
      claims := jsonb_set(claims, '{user_role}', 'null');
    end if;

    -- Update the 'claims' object in the original event
    event := jsonb_set(event, '{claims}', claims);

    -- Return the modified or original event
    return event;
  end;
$function$
;

create materialized view "public"."movies_fts" as  SELECT m.id,
    m.name,
    m.original_name,
    m.dvd_id,
    m.release_date,
    m.popularity,
    m.create_time,
    s.name AS studio_name,
    s.original_name AS studio_original_name,
    se.name AS series_name,
    se.original_name AS series_original_name,
    l.name AS label_name,
    l.original_name AS label_original_name,
    string_agg(DISTINCT (p.name)::text, ', '::text) AS person_names,
    string_agg(DISTINCT (p.original_name)::text, ', '::text) AS person_original_names,
    (to_tsvector('english'::regconfig, (((((((((((COALESCE(m.name, ''::character varying))::text || ' '::text) || (COALESCE(m.dvd_id, ''::character varying))::text) || ' '::text) || (COALESCE(s.name, ''::character varying))::text) || ' '::text) || (COALESCE(se.name, ''::character varying))::text) || ' '::text) || (COALESCE(l.name, ''::character varying))::text) || ' '::text) || COALESCE(string_agg(DISTINCT (p.name)::text, ', '::text), ''::text))) || to_tsvector('simple'::regconfig, (((((((((COALESCE(m.original_name, ''::character varying))::text || ' '::text) || (COALESCE(s.original_name, ''::character varying))::text) || ' '::text) || (COALESCE(se.original_name, ''::character varying))::text) || ' '::text) || (COALESCE(l.original_name, ''::character varying))::text) || ' '::text) || COALESCE(string_agg(DISTINCT (p.original_name)::text, ', '::text), ''::text)))) AS fts_vector
   FROM (((((movies m
     LEFT JOIN studios s ON ((m.studio_id = s.id)))
     LEFT JOIN series se ON ((m.series_id = se.id)))
     LEFT JOIN labels l ON ((m.label_id = l.id)))
     LEFT JOIN roles r ON ((m.id = r.movie_id)))
     LEFT JOIN persons p ON ((r.person_id = p.id)))
  GROUP BY m.id, s.name, s.original_name, se.name, se.original_name, l.name, l.original_name;


create or replace view "public"."movies_missing_info" as  SELECT movies.id,
    movies.name,
    movies.original_name,
    movies.release_date,
    movies.dvd_id,
    movies.front_cover_url
   FROM movies
  WHERE ((movies.release_date IS NULL) OR (movies.name IS NULL) OR (movies.length IS NULL) OR (movies.studio_id IS NULL) OR (NOT (EXISTS ( SELECT 1
           FROM movie_images
          WHERE (movie_images.movie_id = movies.id)))) OR (NOT (EXISTS ( SELECT 1
           FROM roles
          WHERE (roles.movie_id = movies.id)))))
  ORDER BY (((('x'::text || substr(md5(((movies.id)::text || to_char((CURRENT_DATE)::timestamp with time zone, 'YYYY-MM-DD'::text))), 1, 16)))::bit(64))::bigint)
 LIMIT 25;


create or replace view "public"."movies_per_year" as  SELECT EXTRACT(year FROM movies.release_date) AS release_year,
    count(*) AS movie_count
   FROM movies
  WHERE (movies.release_date IS NOT NULL)
  GROUP BY (EXTRACT(year FROM movies.release_date))
  ORDER BY (EXTRACT(year FROM movies.release_date));


create or replace view "public"."movies_recently_released" as  SELECT movies.id,
    movies.name,
    movies.original_name,
    movies.dvd_id,
    movies.front_cover_url
   FROM movies
  WHERE (movies.release_date <= CURRENT_DATE)
  ORDER BY movies.release_date DESC, movies.dvd_id DESC
 LIMIT 25;


create or replace view "public"."movies_released_today" as  SELECT movies.id,
    movies.create_time,
    movies.update_time,
    movies.name,
    movies.original_name,
    movies.release_date,
    movies.dvd_id,
    movies.length,
    movies.label_id,
    movies.series_id,
    movies.studio_id,
    movies.front_cover_url
   FROM movies
  WHERE ((EXTRACT(month FROM movies.release_date) = EXTRACT(month FROM CURRENT_DATE)) AND (EXTRACT(day FROM movies.release_date) = EXTRACT(day FROM CURRENT_DATE)) AND (EXTRACT(year FROM movies.release_date) < EXTRACT(year FROM CURRENT_DATE)))
  ORDER BY (((('x'::text || substr(md5(((movies.id)::text || to_char((CURRENT_DATE)::timestamp with time zone, 'YYYY-MM-DD'::text))), 1, 16)))::bit(64))::bigint)
 LIMIT 25;


create or replace view "public"."persons_ordered_by_roles" as  SELECT persons.name,
    persons.original_name,
    persons.birth_date,
    count(roles.id) AS role_count
   FROM (persons
     LEFT JOIN roles ON ((persons.id = roles.person_id)))
  GROUP BY persons.id
  ORDER BY (count(roles.id)) DESC;


CREATE OR REPLACE FUNCTION public.refresh_materialized_views()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    view_record RECORD;
BEGIN
    FOR view_record IN
        SELECT matviewname
        FROM pg_matviews
        WHERE schemaname = 'public'
    LOOP
        EXECUTE format('REFRESH MATERIALIZED VIEW %I;', view_record.matviewname);
    END LOOP;
END;
$function$
;

create materialized view "public"."roles_by_age" as  SELECT roles.age,
    count(*) AS count
   FROM roles
  WHERE (roles.age IS NOT NULL)
  GROUP BY roles.age
  ORDER BY roles.age;


CREATE OR REPLACE FUNCTION public.search_movies(search_query text, role_age smallint DEFAULT NULL::smallint, query_offset integer DEFAULT 0, query_limit integer DEFAULT 25)
 RETURNS TABLE(id bigint, name text, original_name text, dvd_id text, release_date timestamp with time zone, front_cover_url text)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY EXECUTE format(
        'SELECT 
            m.id,
            m.name,
            m.original_name,
            m.dvd_id,
            m.release_date,
            m.front_cover_url
        FROM 
            public.movies m
        JOIN 
            public.movies_fts fts ON m.id = fts.id
        LEFT JOIN 
            public.roles r ON m.id = r.movie_id
        WHERE 
            fts.fts_vector @@ to_tsquery(%L)
            AND (%L IS NULL OR r.age = %L)
        LIMIT %L OFFSET %L',
        search_query,
        role_age,
        role_age,
        query_limit,
        query_offset
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.search_movies(search_query text, role_age smallint DEFAULT NULL::smallint, sort_by text DEFAULT 'relevance'::text, sort_order text DEFAULT 'DESC'::text)
 RETURNS TABLE(id bigint, name text, original_name text, dvd_id text, release_date timestamp with time zone, front_cover_url text)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY EXECUTE format(
        'SELECT 
            m.id,
            m.name,
            m.original_name,
            m.dvd_id,
            m.release_date,
            m.front_cover_url
        FROM 
            public.movies m
        JOIN 
            public.movies_fts fts ON m.id = fts.id
        LEFT JOIN 
            public.roles r ON m.id = r.movie_id
        WHERE 
            fts.fts_vector @@ to_tsquery(%L)
            AND (%L IS NULL OR r.age = %L)
        ORDER BY 
            CASE 
                WHEN %L = ''popularity'' THEN m.popularity
                WHEN %L = ''create_time'' THEN m.create_time
                WHEN %L = ''dvd_id'' THEN m.dvd_id
                WHEN %L = ''release_date'' THEN m.release_date
                ELSE ts_rank(fts.fts_vector, to_tsquery(%L))
            END 
            COLLATE "C" %s',
        search_query,
        role_age,
        role_age,
        sort_by,
        sort_by,
        sort_by,
        sort_by,
        search_query,
        sort_order
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.search_movies(search_query text, role_age smallint DEFAULT NULL::smallint, sort_by text DEFAULT 'relevance'::text, sort_order text DEFAULT 'desc'::text, query_offset integer DEFAULT 0, query_limit integer DEFAULT 25)
 RETURNS TABLE(id bigint, name text, original_name text, dvd_id text, release_date timestamp with time zone, front_cover_url text)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY EXECUTE format(
        'SELECT 
            m.id,
            m.name,
            m.original_name,
            m.dvd_id,
            m.release_date,
            m.front_cover_url
        FROM 
            public.movies m
        JOIN 
            public.movies_fts fts ON m.id = fts.id
        LEFT JOIN 
            public.roles r ON m.id = r.movie_id
        WHERE 
            fts.fts_vector @@ to_tsquery(%L)
            AND (%L IS NULL OR r.age = %L)
        ORDER BY 
            CASE 
                WHEN %L = ''popularity'' THEN m.popularity
                WHEN %L = ''create_time'' THEN m.create_time
                WHEN %L = ''dvd_id'' THEN m.dvd_id
                WHEN %L = ''release_date'' THEN m.release_date
                ELSE ts_rank(fts.fts_vector, to_tsquery(%L))
            END 
            COLLATE "C" %s
        LIMIT %L OFFSET %L',
        search_query,
        role_age,
        role_age,
        sort_by,
        sort_by,
        sort_by,
        sort_by,
        search_query,
        sort_order,
        query_limit,
        query_offset
    );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_random_seed(seed double precision)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
begin
  perform setseed(seed);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.update_movie_cover_url()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    image_uuid text;
    image_type public.image_type;  -- Assuming 'public.image_type' is the name of the enum type
BEGIN
    -- Retrieve the UUID and type from the images table based on the image_id
    SELECT uuid, type INTO image_uuid, image_type FROM images WHERE id = NEW.image_id;

    IF image_type = 'front_cover'::public.image_type AND (SELECT front_cover_url FROM movies WHERE id = NEW.movie_id) IS NULL THEN
        UPDATE movies
        SET front_cover_url = image_uuid
        WHERE id = NEW.movie_id;
    ELSIF image_type = 'full_cover'::public.image_type AND (SELECT full_cover_url FROM movies WHERE id = NEW.movie_id) IS NULL THEN
        UPDATE movies
        SET full_cover_url = image_uuid
        WHERE id = NEW.movie_id;
    END IF;

    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_movie_popularity()
 RETURNS void
 LANGUAGE plpgsql
AS $function$DECLARE
    movie_record RECORD;
    views_yesterday bigint;
    days_since_release float;
    weight_views float := 0.5; -- Weight for views
    weight_release float := 0.3; -- Weight for release date
    weight_current_popularity float := 0.2; -- Weight for current popularity
BEGIN
    FOR movie_record IN 
        SELECT id, release_date, popularity
        FROM public.movies
    LOOP
        -- Get the number of views for the movie from the previous day
        SELECT COUNT(*)
        INTO views_yesterday
        FROM public.views
        WHERE item_id = movie_record.id
          AND item_type = 'movie'
          AND date = CURRENT_DATE - INTERVAL '1 day';

        -- Calculate days since release
        days_since_release := 
            CASE 
                WHEN movie_record.release_date IS NULL THEN 10000::float
                WHEN movie_record.release_date > CURRENT_DATE THEN 10000::float
                ELSE EXTRACT(DAY FROM CURRENT_DATE - movie_record.release_date)::float
            END;

        -- Calculate new popularity
        movie_record.popularity := 
            (views_yesterday::float * weight_views) +
            (1.0 / (1::float + days_since_release) * weight_release) + 
            (movie_record.popularity * weight_current_popularity);

        -- Update the movie's popularity
        UPDATE public.movies
        SET popularity = movie_record.popularity
        WHERE id = movie_record.id;
    END LOOP;
END;$function$
;

CREATE OR REPLACE FUNCTION public.update_movie_popularity(limit_val integer, offset_val integer)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
DECLARE
    movie_record RECORD;
    views_yesterday bigint;
    days_since_release float;
    weight_views float := 0.5; -- Weight for views
    weight_release float := 0.3; -- Weight for release date
    weight_current_popularity float := 0.2; -- Weight for current popularity
BEGIN
    FOR movie_record IN 
        SELECT id, release_date, popularity
        FROM public.movies
        ORDER BY id  -- Ensuring consistent ordering
        LIMIT limit_val
        OFFSET offset_val
    LOOP
        -- Get the number of views for the movie from the previous day
        SELECT COUNT(*)
        INTO views_yesterday
        FROM public.views
        WHERE item_id = movie_record.id
          AND item_type = 'movie'
          AND date = CURRENT_DATE - INTERVAL '1 day';

        -- Calculate days since release
        days_since_release := 
            CASE 
                WHEN movie_record.release_date IS NULL THEN 10000::float
                WHEN movie_record.release_date > CURRENT_DATE THEN 10000::float
                ELSE EXTRACT(DAY FROM CURRENT_DATE - movie_record.release_date)::float
            END;

        -- Calculate new popularity
        movie_record.popularity := 
            (views_yesterday::float * weight_views) +
            (1.0 / (1::float + days_since_release) * weight_release) + 
            (movie_record.popularity * weight_current_popularity);

        -- Update the movie's popularity
        UPDATE public.movies
        SET popularity = movie_record.popularity
        WHERE id = movie_record.id;
    END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_person_popularity()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    person_record RECORD;
    weight_views float := 0.7;  
    weight_current_popularity float := 0.3;
    total_views BIGINT;
BEGIN
    -- Loop through each person in the persons table
    FOR person_record IN SELECT id FROM public.persons LOOP
        -- Count the number of views for the current person in the previous day
        SELECT COUNT(*) INTO total_views
        FROM public.views
        WHERE item_type = 'person' AND item_id = person_record.id
        AND date = CURRENT_DATE - INTERVAL '1 day';

        -- Update the popularity score based on views and current popularity
        UPDATE public.persons
        SET popularity = (weight_views * total_views::float) + (weight_current_popularity * COALESCE(popularity, 0::float))
        WHERE id = person_record.id;
    END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$declare gravatar_url text;
begin
  gravatar_url := 'https://www.gravatar.com/avatar/' || md5(new.email) || '?d=404';

  insert into public.profiles (id, username, avatar_url, email)
  values (new.id, new.raw_user_meta_data ->> 'full_name', gravatar_url, new.email);
  insert into public.user_roles (user_id, role)
  values (new.id, 'user'::public.app_role);
  return new;
end;$function$
;

CREATE OR REPLACE FUNCTION public.persons_movies_count(persons)
 RETURNS bigint
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
  select count(*) from public.roles where person_id = $1.id;
$function$
;

CREATE OR REPLACE FUNCTION public.series_movies_count(series)
 RETURNS bigint
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
  select count(*) from public.movies where series_id = $1.id;
$function$
;

CREATE OR REPLACE FUNCTION public.studio_movies_count(studios)
 RETURNS bigint
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$
  select count(*) from public.movies where studio_id = $1.id;
$function$
;

CREATE OR REPLACE FUNCTION public.update_role_age_create()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$BEGIN
  DECLARE
    movie_record RECORD;
    person_record RECORD;
    new_age INT;
  BEGIN
    SELECT * INTO movie_record
    FROM public.movies
    WHERE movies.id = NEW.movie_id;

    SELECT * INTO person_record
    FROM public.persons
    WHERE persons.id = NEW.person_id;

    -- Calculate age using date arithmetic
    new_age := EXTRACT(YEAR FROM AGE(movie_record.release_date, person_record.birth_date));

    UPDATE public.roles
    SET age = new_age
    WHERE id = NEW.id;

    RETURN NEW;
  END;
END;$function$
;

CREATE OR REPLACE FUNCTION public.update_role_age_movies()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
BEGIN
    UPDATE public.roles 
    SET age = EXTRACT(YEAR FROM AGE(NEW.release_date, persons.birth_date))
    FROM public.persons
    WHERE roles.movie_id = NEW.id AND roles.person_id = persons.id;

    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_role_age_persons()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Update the age column in roles table
    UPDATE public.roles r
    SET age = EXTRACT(YEAR FROM AGE(m.release_date, NEW.birth_date))
    FROM public.movies m
    WHERE r.person_id = NEW.id
    AND r.movie_id = m.id
    AND NEW.birth_date IS NOT NULL
    AND m.release_date IS NOT NULL;

    RETURN NEW;
END;
$function$
;

grant delete on table "public"."images" to "anon";

grant insert on table "public"."images" to "anon";

grant references on table "public"."images" to "anon";

grant select on table "public"."images" to "anon";

grant trigger on table "public"."images" to "anon";

grant truncate on table "public"."images" to "anon";

grant update on table "public"."images" to "anon";

grant delete on table "public"."images" to "authenticated";

grant insert on table "public"."images" to "authenticated";

grant references on table "public"."images" to "authenticated";

grant select on table "public"."images" to "authenticated";

grant trigger on table "public"."images" to "authenticated";

grant truncate on table "public"."images" to "authenticated";

grant update on table "public"."images" to "authenticated";

grant delete on table "public"."images" to "service_role";

grant insert on table "public"."images" to "service_role";

grant references on table "public"."images" to "service_role";

grant select on table "public"."images" to "service_role";

grant trigger on table "public"."images" to "service_role";

grant truncate on table "public"."images" to "service_role";

grant update on table "public"."images" to "service_role";

grant delete on table "public"."movie_images" to "anon";

grant insert on table "public"."movie_images" to "anon";

grant references on table "public"."movie_images" to "anon";

grant select on table "public"."movie_images" to "anon";

grant trigger on table "public"."movie_images" to "anon";

grant truncate on table "public"."movie_images" to "anon";

grant update on table "public"."movie_images" to "anon";

grant delete on table "public"."movie_images" to "authenticated";

grant insert on table "public"."movie_images" to "authenticated";

grant references on table "public"."movie_images" to "authenticated";

grant select on table "public"."movie_images" to "authenticated";

grant trigger on table "public"."movie_images" to "authenticated";

grant truncate on table "public"."movie_images" to "authenticated";

grant update on table "public"."movie_images" to "authenticated";

grant delete on table "public"."movie_images" to "service_role";

grant insert on table "public"."movie_images" to "service_role";

grant references on table "public"."movie_images" to "service_role";

grant select on table "public"."movie_images" to "service_role";

grant trigger on table "public"."movie_images" to "service_role";

grant truncate on table "public"."movie_images" to "service_role";

grant update on table "public"."movie_images" to "service_role";

grant delete on table "public"."person_images" to "anon";

grant insert on table "public"."person_images" to "anon";

grant references on table "public"."person_images" to "anon";

grant select on table "public"."person_images" to "anon";

grant trigger on table "public"."person_images" to "anon";

grant truncate on table "public"."person_images" to "anon";

grant update on table "public"."person_images" to "anon";

grant delete on table "public"."person_images" to "authenticated";

grant insert on table "public"."person_images" to "authenticated";

grant references on table "public"."person_images" to "authenticated";

grant select on table "public"."person_images" to "authenticated";

grant trigger on table "public"."person_images" to "authenticated";

grant truncate on table "public"."person_images" to "authenticated";

grant update on table "public"."person_images" to "authenticated";

grant delete on table "public"."person_images" to "service_role";

grant insert on table "public"."person_images" to "service_role";

grant references on table "public"."person_images" to "service_role";

grant select on table "public"."person_images" to "service_role";

grant trigger on table "public"."person_images" to "service_role";

grant truncate on table "public"."person_images" to "service_role";

grant update on table "public"."person_images" to "service_role";

grant delete on table "public"."persons_aliases" to "anon";

grant insert on table "public"."persons_aliases" to "anon";

grant references on table "public"."persons_aliases" to "anon";

grant select on table "public"."persons_aliases" to "anon";

grant trigger on table "public"."persons_aliases" to "anon";

grant truncate on table "public"."persons_aliases" to "anon";

grant update on table "public"."persons_aliases" to "anon";

grant delete on table "public"."persons_aliases" to "authenticated";

grant insert on table "public"."persons_aliases" to "authenticated";

grant references on table "public"."persons_aliases" to "authenticated";

grant select on table "public"."persons_aliases" to "authenticated";

grant trigger on table "public"."persons_aliases" to "authenticated";

grant truncate on table "public"."persons_aliases" to "authenticated";

grant update on table "public"."persons_aliases" to "authenticated";

grant delete on table "public"."persons_aliases" to "service_role";

grant insert on table "public"."persons_aliases" to "service_role";

grant references on table "public"."persons_aliases" to "service_role";

grant select on table "public"."persons_aliases" to "service_role";

grant trigger on table "public"."persons_aliases" to "service_role";

grant truncate on table "public"."persons_aliases" to "service_role";

grant update on table "public"."persons_aliases" to "service_role";

grant delete on table "public"."role_permissions" to "anon";

grant insert on table "public"."role_permissions" to "anon";

grant references on table "public"."role_permissions" to "anon";

grant select on table "public"."role_permissions" to "anon";

grant trigger on table "public"."role_permissions" to "anon";

grant truncate on table "public"."role_permissions" to "anon";

grant update on table "public"."role_permissions" to "anon";

grant delete on table "public"."role_permissions" to "authenticated";

grant insert on table "public"."role_permissions" to "authenticated";

grant references on table "public"."role_permissions" to "authenticated";

grant select on table "public"."role_permissions" to "authenticated";

grant trigger on table "public"."role_permissions" to "authenticated";

grant truncate on table "public"."role_permissions" to "authenticated";

grant update on table "public"."role_permissions" to "authenticated";

grant delete on table "public"."role_permissions" to "service_role";

grant insert on table "public"."role_permissions" to "service_role";

grant references on table "public"."role_permissions" to "service_role";

grant select on table "public"."role_permissions" to "service_role";

grant trigger on table "public"."role_permissions" to "service_role";

grant truncate on table "public"."role_permissions" to "service_role";

grant update on table "public"."role_permissions" to "service_role";

grant delete on table "public"."tags" to "anon";

grant insert on table "public"."tags" to "anon";

grant references on table "public"."tags" to "anon";

grant select on table "public"."tags" to "anon";

grant trigger on table "public"."tags" to "anon";

grant truncate on table "public"."tags" to "anon";

grant update on table "public"."tags" to "anon";

grant delete on table "public"."tags" to "authenticated";

grant insert on table "public"."tags" to "authenticated";

grant references on table "public"."tags" to "authenticated";

grant select on table "public"."tags" to "authenticated";

grant trigger on table "public"."tags" to "authenticated";

grant truncate on table "public"."tags" to "authenticated";

grant update on table "public"."tags" to "authenticated";

grant delete on table "public"."tags" to "service_role";

grant insert on table "public"."tags" to "service_role";

grant references on table "public"."tags" to "service_role";

grant select on table "public"."tags" to "service_role";

grant trigger on table "public"."tags" to "service_role";

grant truncate on table "public"."tags" to "service_role";

grant update on table "public"."tags" to "service_role";

grant delete on table "public"."user_roles" to "anon";

grant insert on table "public"."user_roles" to "anon";

grant references on table "public"."user_roles" to "anon";

grant select on table "public"."user_roles" to "anon";

grant trigger on table "public"."user_roles" to "anon";

grant truncate on table "public"."user_roles" to "anon";

grant update on table "public"."user_roles" to "anon";

grant delete on table "public"."user_roles" to "authenticated";

grant insert on table "public"."user_roles" to "authenticated";

grant references on table "public"."user_roles" to "authenticated";

grant select on table "public"."user_roles" to "authenticated";

grant trigger on table "public"."user_roles" to "authenticated";

grant truncate on table "public"."user_roles" to "authenticated";

grant update on table "public"."user_roles" to "authenticated";

grant delete on table "public"."user_roles" to "service_role";

grant insert on table "public"."user_roles" to "service_role";

grant references on table "public"."user_roles" to "service_role";

grant select on table "public"."user_roles" to "service_role";

grant trigger on table "public"."user_roles" to "service_role";

grant truncate on table "public"."user_roles" to "service_role";

grant update on table "public"."user_roles" to "service_role";

grant delete on table "public"."user_roles" to "supabase_auth_admin";

grant insert on table "public"."user_roles" to "supabase_auth_admin";

grant references on table "public"."user_roles" to "supabase_auth_admin";

grant select on table "public"."user_roles" to "supabase_auth_admin";

grant trigger on table "public"."user_roles" to "supabase_auth_admin";

grant truncate on table "public"."user_roles" to "supabase_auth_admin";

grant update on table "public"."user_roles" to "supabase_auth_admin";

grant delete on table "public"."views" to "anon";

grant insert on table "public"."views" to "anon";

grant references on table "public"."views" to "anon";

grant select on table "public"."views" to "anon";

grant trigger on table "public"."views" to "anon";

grant truncate on table "public"."views" to "anon";

grant update on table "public"."views" to "anon";

grant delete on table "public"."views" to "authenticated";

grant insert on table "public"."views" to "authenticated";

grant references on table "public"."views" to "authenticated";

grant select on table "public"."views" to "authenticated";

grant trigger on table "public"."views" to "authenticated";

grant truncate on table "public"."views" to "authenticated";

grant update on table "public"."views" to "authenticated";

grant delete on table "public"."views" to "service_role";

grant insert on table "public"."views" to "service_role";

grant references on table "public"."views" to "service_role";

grant select on table "public"."views" to "service_role";

grant trigger on table "public"."views" to "service_role";

grant truncate on table "public"."views" to "service_role";

grant update on table "public"."views" to "service_role";

create policy "Enable read access for all users"
on "public"."images"
as permissive
for all
to public
using (true);


create policy "Allow authorized users insert access"
on "public"."movie_images"
as permissive
for insert
to public
with check (( SELECT authorize('movie.update'::app_permission) AS authorize));


create policy "Enable read access for all users"
on "public"."movie_images"
as permissive
for select
to public
using (true);


create policy "Allow authorized delete access"
on "public"."movies"
as permissive
for delete
to public
using (( SELECT authorize('movie.delete'::app_permission) AS authorize));


create policy "Allow authorized insert access"
on "public"."movies"
as permissive
for insert
to public
with check (( SELECT authorize('movie.create'::app_permission) AS authorize));


create policy "Allow authorized update access"
on "public"."movies"
as permissive
for update
to public
using (( SELECT authorize('movie.update'::app_permission) AS authorize));


create policy "Allow authorized users insert access"
on "public"."person_images"
as permissive
for insert
to public
with check (( SELECT authorize('person.update'::app_permission) AS authorize));


create policy "Enable read access for all users"
on "public"."person_images"
as permissive
for select
to public
using (true);


create policy "Allow authorized delete access"
on "public"."persons"
as permissive
for delete
to public
using (( SELECT authorize('person.update'::app_permission) AS authorize));


create policy "Allow authorized update access"
on "public"."persons"
as permissive
for update
to public
using (( SELECT authorize('person.update'::app_permission) AS authorize));


create policy "Enable read access for all users"
on "public"."persons_aliases"
as permissive
for select
to public
using (true);


create policy "Allow auth admin to read user roles"
on "public"."role_permissions"
as permissive
for select
to supabase_auth_admin
using (true);


create policy "Allow delete for authorized"
on "public"."roles"
as permissive
for delete
to public
using (( SELECT authorize('role.delete'::app_permission) AS authorize));


create policy "Enable insert for authorized users"
on "public"."roles"
as permissive
for insert
to public
with check (( SELECT authorize('role.create'::app_permission) AS authorize));


create policy "Enable read access for all users"
on "public"."tags"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."user_roles"
as permissive
for select
to public
using (true);


create policy "Enable insert access for all users"
on "public"."views"
as permissive
for insert
to public
with check (true);


CREATE TRIGGER set_movie_cover_url AFTER INSERT ON public.movie_images FOR EACH ROW EXECUTE FUNCTION update_movie_cover_url();

CREATE TRIGGER update_role_age_persons_trigger AFTER UPDATE ON public.persons FOR EACH ROW EXECUTE FUNCTION update_role_age_persons();


